### ISSUE TITLE
连接尝试失败

### ISSUE THREAD

**Issue by liangjianfeng-av** [emptysuns/18comic-Download#6]
本人小白，请见谅。配置好python后，打开Catch18comic.py，输入网址解析成功开始就显示”由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。”
1. 是否是18comic进行了反扒？地址如下 https://18comic2.one/photo/239508/
2. 在win32 下打包成exe ，提示“文件未找到cacert.pem resource not found in pip._vendor” 哪里错了吗？环境为win7-32 sp1，python-3.8.7，pip 21.0.1，setuptool 49.2.1，xml已安装
3. 依赖库方面，beautifulsoup已经升级为beautifulsoup4，PIL已升级为pillow。

**Comment by emptysuns** [comment]
新年快乐！除夕您还在下h manga吗？！
shock me😂(放过我吧，大年初一的)
言归正传...
鉴于您说的连接失败的问题，而且
估计您在国内。
首先判断您的梯子是否能正常访问该网站，我指的是您的https和http协议是否走代理。
其次，我在程序中的禁漫天堂是根据18comic.org 或 18comic.vip写的。在issue中指出的和我适配的是镜像站？
请再次尝试用如上两个网站进行测试。
谢谢提出使用问题。

**Comment by emptysuns** [comment]
还有如果想测试脚本请使用Python3.7版本，3.8版本打包报错是pyinstaller这个打包model兼容性不好的，说白了有bug，官方一直未修，请试试3.7.9版本进行测试。
(最后，善意提醒:现阶段最好不要用3.8版本的Python。这个版本现还不太稳定，在我使用过程中也出现过一些莫名其妙的玄学问题，换成3.7完美解决。)

**Comment by liangjianfeng-av** [comment]
新年快乐！感谢大佬回复。PS，放假才有时间研究这个下H manga啊^ _^
1. 卸载3.8.7后，安装3.7.9，依旧存在上诉问题。打包时是成功的，但运行有问题。
环境：PyInstaller: 4.2，Python: 3.7.9， Windows-7-6.1.7601-SP1，wrote C:\Users\Administrator\Catch18comic.spec，UPX is not available.
用cmd运行exe显示：
  File "importlib\resources.py", line 97, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\Ap
pData\\Local\\Temp\\_MEI43602\\pip\\_vendor\\certifi\\cacert.pem'
FileNotFoundError: 'cacert.pem' resource not found in 'pip._vendor.certifi'
[4476] Failed to execute script Catch18comic
2. 挂了全局代理的梯子，网页可以正常打开观看。使用的例子提供的https://18comic.org/photo/232758/，直接cmd运行py，可以运行，但连接一段时间，会提示超时和错误
File "C:\Users\Administrator\requests\adapters.py", line 449, in send timeout=timeout
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)

**Comment by emptysuns** [comment]
这是我最新的测试截图：
https://s3.ax1x.com/2021/02/13/yrhxoQ.png
先阶段这脚本在我这里是没任何问题的。对于您如上提出的问题：
1、打包后无法运行的问题。通过您的反馈，我大致猜测应该是缺少https认证文件的问题。
个人猜测，请问您是否是用
`pyinstaller Catch18comic.py`
而不是
`pyinstaller --onefile Catch18comic.py`
进行打包的呢？ 
或者您未打包成一个文件，但是打包后的exe，未在原目录运行呢？从提供的debug信息只能分析到这里了。
2、关于超时问题解释。
ssl error这个问题，我能力有限，我无法复现这个问题和从来没有遇到过这种情况。不过，个人见解这应该是您梯子的问题了，为何不能尝试换一个节点进行测试呢。如果再出错能否给出完整的报错信息，只有一枝半叶，很难确定问题发生在哪里，理论上，我在下载时做了差错检测，如果下载失败应该会重新下载的。但是您所指出报错的异常未被捕获，我想应该有全部的报错更能确定问题所在。

**Comment by liangjianfeng-av** [comment]
感谢大佬回复。
1. 用的是pyinstaller --onefile Catch18comic.py。另外，测试过其他文件打包，依然会出现上述的cacert.pem问题。我猜测和您的程序无关，可能和我的环境或者方法有关。从官网下载安装python-3.7.9后，使用了以下命令python -m pip install --upgrade pip
，pip install --upgrade setuptools，pip3 install lxml，pip install pyinstaller，pip3 install beautifulsoup4，pip3 install pillow
，pyinstaller --onefile Catch18comic.py。另外测试另外打包一个文件，又使用了pip install fake-useragent。（1）打包的时候已将requests文件夹从C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\pip\_vendor复制到C:\Users\Administrator。（2）Catch18comic.py和README.md在C:\Users\Administrator\下（3）运行程序是在C:\Users\Administrator\dist下的Catch18comic.exe。
（4）以下是CMD下打包全文
---------------------------------------------------------------------
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>pyinstaller --onefile Catch18comic.py
568 INFO: PyInstaller: 4.2
569 INFO: Python: 3.7.9
569 INFO: Platform: Windows-7-6.1.7601-SP1
572 INFO: wrote C:\Users\Administrator\Catch18comic.spec
577 INFO: UPX is not available.
580 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Administrator', 'C:\\Users\\Administrator']
802 INFO: checking Analysis
2023 INFO: checking PYZ
2335 INFO: checking PKG
2378 INFO: Building because C:\Users\Administrator\build\Catch18comic\Catch18com
ic.exe.manifest changed
2379 INFO: Building PKG (CArchive) PKG-00.pkg
7314 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
7344 INFO: Bootloader c:\users\administrator\appdata\local\programs\python\pytho
n37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
7345 INFO: checking EXE
7370 INFO: Rebuilding EXE-00.toc because Catch18comic.exe missing
7371 INFO: Building EXE from EXE-00.toc
7407 INFO: Copying icons from ['c:\\users\\administrator\\appdata\\local\\progra
ms\\python\\python37-32\\lib\\site-packages\\PyInstaller\\bootloader\\images\\ic
on-console.ico']
7428 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
7428 INFO: Writing RT_ICON 1 resource with 3752 bytes
7429 INFO: Writing RT_ICON 2 resource with 2216 bytes
7430 INFO: Writing RT_ICON 3 resource with 1384 bytes
7430 INFO: Writing RT_ICON 4 resource with 37019 bytes
7431 INFO: Writing RT_ICON 5 resource with 9640 bytes
7432 INFO: Writing RT_ICON 6 resource with 4264 bytes
7433 INFO: Writing RT_ICON 7 resource with 1128 bytes
7443 INFO: Updating manifest in C:\Users\Administrator\build\Catch18comic\run.ex
e.omjjdqfu
7445 INFO: Updating resource type 24 name 1 language 0
7453 INFO: Appending archive to EXE C:\Users\Administrator\dist\Catch18comic.exe

7477 INFO: Building EXE from EXE-00.toc completed successfully.

C:\Users\Administrator>
------------------------------------------------
（5）CMD下运行程序全文
---------------------------------------------------
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>C:\Users\Administrator\dist\Catch18comic.exe
Traceback (most recent call last):
  File "importlib\resources.py", line 97, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\Ap
pData\\Local\\Temp\\_MEI42962\\pip\\_vendor\\certifi\\cacert.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Catch18comic.py", line 1, in <module>
    from requests import *
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "requests\__init__.py", line 123, in <module>
    from . import utils
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "requests\utils.py", line 40, in <module>
    DEFAULT_CA_BUNDLE_PATH = certs.where()
  File "pip\_vendor\certifi\core.py", line 37, in where
  File "contextlib.py", line 112, in __enter__
  File "importlib\resources.py", line 201, in path
  File "importlib\resources.py", line 111, in open_binary
FileNotFoundError: 'cacert.pem' resource not found in 'pip._vendor.certifi'
[4908] Failed to execute script Catch18comic

C:\Users\Administrator>

**Comment by liangjianfeng-av** [comment]
2. cmd中直接运行C:\Users\Administrator\Catch18comic.py，梯子更换不同节点，报错相同。查看v2rayN梯子上的数据流，一直是0  K。但网页版的18comic是正常的，其他程序全局代理也正常。在此情况下，测试使用其他的文件程序连接下载18comic，能连接，能下载，但是因为并没有做反扒处理，导致下载的图片是红色条纹切割状。此时v2rayN是有流量的。
-----------------------------------------------------------------------------
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>C:\Users\Administrator\Catch18comic.py
18comic.vip Downloader by emptysuns.
请不要用于任何非法用途，仅作学习交流
版本:Version 2.2
下载链接格式请参照：
https://github.com/emptysuns/18comic-Download   https://blog.acglove.cloud/?p=35


第1次下载,请输入您想要下载comic的下载链接:
https://18comic.org/photo/232758/
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\pip\_vendor\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\pip\_vendor\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\pip\_vendor\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\pip\_vendor\urllib3\connection.py", line 502, in _connect_tls_proxy
    ssl_context=ssl_context,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\pip\_vendor\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\pip\_vendor\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl

    return ssl_context.wrap_socket(sock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl
.py", line 423, in wrap_socket
    session=session
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl
.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\ssl
.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\pip\_vendor\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\pip\_vendor\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
pip._vendor.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='18comic.
org', port=443): Max retries exceeded with url: /photo/232758/ (Caused by SSLErr
or(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)')
))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Catch18comic.py", line 191, in <module>
    flag = checkPluralPage(url)
  File "C:\Users\Administrator\Catch18comic.py", line 118, in checkPluralPage
    response = get(url)
  File "C:\Users\Administrator\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Administrator\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='18comic.org', port=443):
 Max retries exceeded with url: /photo/232758/ (Caused by SSLError(SSLError(1, '
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)')))

C:\Users\Administrator>

**Comment by emptysuns** [comment]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>C:\Users\Administrator\dist\Catch18comic.exe
Traceback (most recent call last):
File "importlib\resources.py", line 97, in open_binary
**FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\ADMINI~1\Ap
pData\Local\Temp\_MEI42962\pip\_vendor\certifi\cacert.pem'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "Catch18comic.py", line 1, in
from requests import *
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
**File "requests_init.py", line 123, in
from . import utils**
File "", line 983, in _find_and_load
File "", line 967, in _find_and_load_unlocked
File "", line 677, in _load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
**File "requests\utils.py", line 40, in
DEFAULT_CA_BUNDLE_PATH = certs.where()**
File "pip_vendor\certifi\core.py", line 37, in where
File "contextlib.py", line 112, in enter
File "importlib\resources.py", line 201, in path
File "importlib\resources.py", line 111, in open_binary
FileNotFoundError: 'cacert.pem' resource not found in 'pip._vendor.certifi'
[4908] Failed to execute script Catch18comic

从上面加黑的几行看出大致看出是requests库中缺少pem文件的问题，也就是https指它无法认证证书，进行身份认证。
但这是如果您使用的python3.7.9的话不会报错的。requests是内置的，应该不会有这种错误？请问是否是从python.org下载的吗？
从报错可以看出这个被打包的代码未有任何问题。您的报错是在requests库初始化时就会有问题，而我只对下载图片时的抛出的异常进行了处理。这应该是异常未被捕获的原因了。所以这是你python环境的问题，正所谓千人千面，这种环境问题我能给予的帮助就很小了，毕竟您的电脑我看不见摸不着，很难诊断。如果使用其他程序不会报错能请求成功，很可能它的程序未使用requests是用urllib直接请求的。

现给出可行解决方案:

-  **_执行之前请检查win7环境变量，cmd下的python命令是否是指向python3.7.9的程序_**
先对requests进行更新
`python -m pip install --upgrade requests`
如果还有问题，那么请尝试
可以试试在cmd内运行:
`python -m pip install --upgrade certifi`
如果提示不存在就:
`python -m pip install certifi`
然后再次尝试！如果还是失败...
cmd下键入python命令进入python控制台
`import certifi
certifi.where()`
查看是否有打印信息例如
`'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\certifi\\cacert.pem'`
如果没有请下载相应pem文件放到参考如上对应文件夹内地址（pem文件:[CA Extract](https://curl.se/ca/cacert.pem)）

- ~~win7的话反正是windows系统不像linux万物皆可日志，有什么玄学的问题都不奇怪，要不重新配置环境，要不重装系统，还能用vmware虚拟一个linux环境进行使用，最后换个电脑解千愁，都2021年了别用32位win7了~~

**Comment by liangjianfeng-av** [comment]
再次感谢大佬的回复。1. 使用 python -m pip install --upgrade requests 已经成功打包exe。exe运行没有出错。
（我也不想用32位win7，但是暂时没能力更换电脑。T——T）
2. A挂了全局梯子依旧无法下载，情况和之前相同。梯子实际上是有768b/s下载与156b/s的上传数据。没有“解析成功”，出ssl.SSLError
    B不使用梯子，没有“解析成功”，出“连接超时”
3. 另外根据http://jmcomic.xyz/和https://trello.com/b/McDZAm8C/%E7%A6%81%E6%BC%AB%E5%A4%A9%E5%A0%82%E5%85%AC%E5%91%8A%E7%89%88-18comicvip
18comic实际上有以下几个站。
https://18comic.vip
https://18comic.org
https://18comic1.one
https://18comic2.one
采用其他域名的连接 则会提示“解析成功,开始下载”，但是最后“由于连接方在一段时间后没有正确答复或连接的
主机没有反应，连接尝试失败”

**是否需要登录18comic才能下载？**

--------------------------
2. A中的记录
--------------------------
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>C:\Users\Administrator\dist\Catch18comic.exe
18comic.vip Downloader by emptysuns.
请不要用于任何非法用途，仅作学习交流
版本:Version 2.2
下载链接格式请参照：
https://github.com/emptysuns/18comic-Download   https://blog.acglove.cloud/?p=35


第1次下载,请输入您想要下载comic的下载链接:
https://18comic.org/photo/232758/
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 502, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
    timeout=timeout
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='18comic.org', port=4
43): Max retries exceeded with url: /photo/232758/ (Caused by SSLError(SSLError(
1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Catch18comic.py", line 191, in <module>
    flag = checkPluralPage(url)
  File "Catch18comic.py", line 118, in checkPluralPage
    response = get(url)
  File "requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='18comic.org', port=443):
 Max retries exceeded with url: /photo/232758/ (Caused by SSLError(SSLError(1, '
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)')))
[6480] Failed to execute script Catch18comic

C:\Users\Administrator>

--------------------------
2. B中的记录
--------------------------

第1次下载,请输入您想要下载comic的下载链接:
https://18comic.org/photo/232758/
Traceback (most recent call last):
  File "urllib3\connection.py", line 170, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没
有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 353, in connect
  File "urllib3\connection.py", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection objec
t at 0x024AF550>: Failed to establish a new connection: [WinError 10060] 由于连
接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
    timeout=timeout
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='18comic.org', port=4
43): Max retries exceeded with url: /photo/232758/ (Caused by NewConnectionError
('<urllib3.connection.HTTPSConnection object at 0x024AF550>: Failed to establish
 a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主
机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Catch18comic.py", line 191, in <module>
    flag = checkPluralPage(url)
  File "Catch18comic.py", line 118, in checkPluralPage
    response = get(url)
  File "requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='18comic.org', por
t=443): Max retries exceeded with url: /photo/232758/ (Caused by NewConnectionEr
ror('<urllib3.connection.HTTPSConnection object at 0x024AF550>: Failed to establ
ish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接
的主机没有反应，连接尝试失败。'))
[2288] Failed to execute script Catch18comic



--------------------------
3. 中的记录
--------------------------

C:\Users\Administrator>C:\Users\Administrator\dist\Catch18comic.exe
18comic.vip Downloader by emptysuns.
请不要用于任何非法用途，仅作学习交流
版本:Version 2.2
下载链接格式请参照：
https://github.com/emptysuns/18comic-Download   https://blog.acglove.cloud/?p=3


第1次下载,请输入您想要下载comic的下载链接:
https://18comic2.one/photo/239508/
解析成功,开始下载 https://18comic.org/photo/239508
Traceback (most recent call last):
  File "urllib3\connection.py", line 170, in _new_conn
  File "urllib3\util\connection.py", line 96, in create_connection
  File "urllib3\util\connection.py", line 86, in create_connection
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没
有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 706, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 353, in connect
  File "urllib3\connection.py", line 182, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection obje
t at 0x0248F970>: Failed to establish a new connection: [WinError 10060] 由于连
接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 449, in send
    timeout=timeout
  File "urllib3\connectionpool.py", line 756, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='18comic.org', port=
43): Max retries exceeded with url: /photo/239508 (Caused by NewConnectionError
'<urllib3.connection.HTTPSConnection object at 0x0248F970>: Failed to establish
a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主
机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Catch18comic.py", line 217, in <module>
    main(id)
  File "Catch18comic.py", line 168, in main
    path = makeDir(url)
  File "Catch18comic.py", line 74, in makeDir
    response = get(url, headers=public_headers)
  File "requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='18comic.org', po
t=443): Max retries exceeded with url: /photo/239508 (Caused by NewConnectionEr
or('<urllib3.connection.HTTPSConnection object at 0x0248F970>: Failed to establ
sh a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的
主机没有反应，连接尝试失败。'))
[6288] Failed to execute script Catch18comic

C:\Users\Administrator>

**Comment by emptysuns** [comment]
你是不是试着更新了那个certifi model了呢。ssl error这个是你握手出错了吧，你再仔细检查一下你代理软件的设置。
或者这代理的节点的问题了，比如你这个是公共共享节点，“万人骑”，这样被网站cdn或者源服务器拉黑名单什么的，连接超时，这个问题就只能你解决了，超出我范围了。有兴趣可以自己搭一个节点使用，也花不了多少钱吧，毕竟自己的放心。
我看debug，觉的就是你本地代理软件设置原因，urllib无法连接，打包后程序未走代理。如果浏览器成功打开了网站，打包后程序不行，你可以去win7全局代理设置那里查看。到这里我就爱莫能助了。

**Comment by liangjianfeng-av** [comment]
使用 python -m pip install --upgrade requests 已经成功打包exe,没有出错了。更新那个certifi model，也提示已存在。
谢谢大佬一直的回复和指导。梯子的问题，我换一个应该能解决的。
再次感谢！
