### ISSUE TITLE
单章页数过多会出错

### ISSUE THREAD

**Issue by liangjianfeng-av** [emptysuns/18comic-Download#7]
大佬，又是我。哈哈哈。
1. 单章超过一定页数（暂时知道是490~500）会出BUG，详细见下面的记录。推测是页数过多，导致线程爆炸，cpu爆了。建议超过一定数量，线程做分批处理。

下面是建议（仅仅是个人的一些想法，勿怪，伸手党本不应该这么多要求）：
2. 下载路径建议放在exe同层目录下download文件夹。如果改成由用户自己输入则每次都需要输入，这十分麻烦。所以同层目录下比较好。
3.  某些漫画可能已经完成了（进入文件夹查看），但是cmd中一直是显示“正在开始多线程下载，请稍后.....”，等了很久也是没有反应的，并不会提示“由于不可抗网络因素下载失败，重新下载”。当然这个只要重新整个下载就可以了。是否需要增加一个超时重新连接？
4. 章节重复问题，如果一个漫画有20多话，下载到10话的时候卡住了，比如上诉的3的情况。这时候只能A，全部重新下载。B手动一个个加地址下载后10个。能否增加话数中间选择？
5. 18comic似乎有流量检测，短时间大流量下载会导致IP封禁一段时间（限速，限连）。此时重新连接就会一直出错。是否能自动走其他分流线路，比如18comic.org不行，就走18comic.vip，18comic1.one，18comic2.one？

-------------------------
第1次下载,请输入您想要下载comic的下载链接:
https://18comic.org/photo/148490
解析成功,开始下载 https://18comic.org/photo/148490
成功创建目录 ./download/深夜便利店 03
正在开始多线程下载（线程数量:495)请稍后......
Exception in thread DownloadPageIs71:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs386:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs351:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs338:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs310:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs67:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs286:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs22:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Traceback (most recent call last):

Exception in thread DownloadPageIs285:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs281:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs58:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 264, in load
    b = b + s
MemoryError
Exception in thread DownloadPageIs82:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2164, in save
    save_handler(self, fp, filename)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\JpegImagePlugin.py", line 761, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 542, in _save
    s = e.encode_to_file(fh, bufsize)
MemoryError
Exception in thread DownloadPageIs257:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 264, in load
    b = b + s
MemoryError
Exception in thread DownloadPageIs109:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 264, in load
    b = b + s
MemoryError
Exception in thread DownloadPageIs289:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 247, in load
    s = read(self.decodermaxblock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\JpegImagePlugin.py", line 399, in load_read
    s = self.fp.read(read_bytes)
MemoryError
Exception in thread DownloadPageIs173:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 264, in load
    b = b + s
MemoryError

Exception in thread DownloadPageIs19:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs194:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 247, in load
    s = read(self.decodermaxblock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\JpegImagePlugin.py", line 399, in load_read
    s = self.fp.read(read_bytes)
MemoryError

Exception in thread DownloadPageIs393:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 247, in load
    s = read(self.decodermaxblock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\JpegImagePlugin.py", line 399, in load_read
    s = self.fp.read(read_bytes)
MemoryError
Exception in thread DownloadPageIs165:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs177:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 264, in load
    b = b + s
MemoryError

Exception in thread DownloadPageIs50:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2164, in save
    save_handler(self, fp, filename)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\JpegImagePlugin.py", line 761, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 542, in _save
    s = e.encode_to_file(fh, bufsize)
MemoryError
Exception in thread DownloadPageIs334:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 247, in load
    s = read(self.decodermaxblock)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\JpegImagePlugin.py", line 399, in load_read
    s = self.fp.read(read_bytes)
MemoryError
Exception in thread DownloadPageIs188:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs344:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs263:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs214:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs398:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs322:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
  File "H:\新建文件夹\Catch18comic-1.py", line 217, in <module>
    main(id)

Exception in thread DownloadPageIs406:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs133:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs361:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs335:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs220:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs227:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment

Exception in thread DownloadPageIs40:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 104, in download_image
    image_bytes = BytesIO(comic_page.content)
UnboundLocalError: local variable 'comic_page' referenced before assignment
Exception in thread DownloadPageIs211:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2164, in save
    save_handler(self, fp, filename)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\JpegImagePlugin.py", line 761, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 542, in _save
    s = e.encode_to_file(fh, bufsize)
MemoryError

Exception in thread DownloadPageIs305:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 264, in load
    b = b + s
MemoryError

Exception in thread DownloadPageIs306:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 926, in 

_bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 870, in 

run
    self._target(*self._args, **self._kwargs)
  File "H:\新建文件夹\Catch18comic-1.py", line 107, in download_image
    image_source.save(comic_local_position)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 2130, in save
    self._ensure_mutable()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 619, in _ensure_mutable
    self._copy()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", 

line 612, in _copy
    self.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL

\ImageFile.py", line 264, in load
    b = b + s
MemoryError
  File "H:\新建文件夹\Catch18comic-1.py", line 176, in main
    downloadByThread(comic_num, url_path_list)

  File "H:\新建文件夹\Catch18comic-1.py", line 155, in downloadByThread
    thread.start()  # 开始线程

RuntimeError: can't start new thread

**Comment by emptysuns** [comment]
在我这里试着500多张没bug，可能我的cpu比较好吧，没注意到，见谅。您的第一个建议的话，如果您使用了2.2版本，应该是自动在本目录创建一个download文件夹的，不会让用户输入。

而且这些问题解决方案您不是都给出来了吗，给的还这么清楚，详细。您可以先自己试试改改代码。我程序实现原理写的非常简单，而且它网站前端也没做什么反爬操作。改的话基本上难度不大。最近没什么太多空闲时间，先鸽一阵时间吧，也不是太严重影响使用了，等一段时间更新。这个issue就这样先留着吧。谢谢反馈问题。
~~我不是因为懒得更新，才说的~~

**Comment by liangjianfeng-av** [comment]
感谢大佬回复。技术有限，修改下载目录和手动分流下载已经是我暂时能做得的极限了。不过确实不大影响使用。期待您的更新。

**Comment by maoyj** [comment]
大部分错误都是网络问题引起的。只要网络好，就不会出现任何错误……
download_image方法中即使遇到网络错误，后续统计页面文件大小时仍然会引用本不存在的comic_page变量。然后后面又会引起一大堆错误

修正后我这边不报错了。
让我多测试几个本子看看 =v=

**Comment by emptysuns** [comment]
有缘再见了
